Display modes and default
j-tesla/tic-tac-toe pull request #16
Opened 2020-10-21 20:17 UTC by koleo

Display available modes and set a default mode ("easy")

2020-10-22 16:39 UTC, j-tesla requested changes

2020-10-22 16:39 UTC, j-tesla commented on tictactoe.py
> +    print("Available modes: " + ", ".join(player_modes))
print it inside the loop

2020-10-22 17:20 UTC, koleo commented on tictactoe.py
> +    print("Available modes: " + ", ".join(player_modes))
done

2020-10-23 05:49 UTC, merged

2020-10-23 05:49 UTC, j-tesla commented
Thanks @koleo :rocket: